//	GainDrive for iOS
//	Copyright (C) 2026 Kasper Peeters
//
//	This file is part of GainDrive, distributed under the GNU General
//	Public License version 3 or later, with the Application Distribution
//	Exception in ios/LICENSE. See LICENSE at the repository root for the
//	full text of the GPL.

import Foundation
import Testing

@testable import GainDrive

/// Reading the subtitles the server sends.
///
/// AVFoundation cannot be handed an external subtitle track at all, so these
/// cues are drawn by the app - which makes this parser the whole of the
/// subtitle feature, and the half of phase 6 that can be got right without a
/// device.
struct WebVTTTests {
	@Test func aPlainFileParses() {
		let cues = WebVTT.parse(
			"""
			WEBVTT

			00:00:01.000 --> 00:00:04.000
			Hello

			00:00:05.500 --> 00:00:07.000
			Goodbye
			"""
		)
		#expect(cues.count == 2)
		#expect(cues.first == Cue(start: 1, end: 4, text: "Hello"))
		#expect(cues.last == Cue(start: 5.5, end: 7, text: "Goodbye"))
	}

	/// **The fraction is a decimal fraction of a second, not milliseconds.**
	/// `00:00.5` is half a second - the same trap the server's `chapters.hh`
	/// calls out.
	@Test func theFractionIsDecimal() {
		#expect(WebVTT.timestamp("00:00.5") == 0.5)
		#expect(WebVTT.timestamp("00:00:00.250") == 0.25)
	}

	@Test func bothTimestampShapesParse() {
		#expect(WebVTT.timestamp("01:02.000") == 62)
		#expect(WebVTT.timestamp("01:00:00.000") == 3600)
		#expect(WebVTT.timestamp("nonsense") == nil)
		#expect(WebVTT.timestamp("1.000") == nil)
	}

	/// **Settings follow the end time on the same line.** Handing the whole
	/// remainder to the timestamp parser fails, and failing there drops the
	/// cue rather than the setting.
	@Test func cueSettingsDoNotSwallowTheCue() {
		let cues = WebVTT.parse(
			"""
			WEBVTT

			00:00:01.000 --> 00:00:02.000 line:0 position:20% align:start
			Placed
			"""
		)
		#expect(cues == [Cue(start: 1, end: 2, text: "Placed")])
	}

	/// A cue identifier, a `NOTE` and a `STYLE` block are all skipped without
	/// being recognised - scanning for the one thing that contains `-->` is
	/// what keeps something unexpected from losing the cues that are fine.
	@Test func headersNotesAndIdentifiersAreSkipped() {
		let cues = WebVTT.parse(
			"""
			WEBVTT - Some title

			NOTE
			This file was generated by something.

			STYLE
			::cue { color: yellow }

			intro
			00:00:01.000 --> 00:00:02.000
			Text
			"""
		)
		#expect(cues == [Cue(start: 1, end: 2, text: "Text")])
	}

	@Test func aCueMaySpanSeveralLines() {
		let cues = WebVTT.parse(
			"""
			WEBVTT

			00:00:01.000 --> 00:00:02.000
			First line
			Second line
			"""
		)
		#expect(cues.first?.text == "First line\nSecond line")
	}

	/// A `\\r` left on the end of a timestamp makes it unparseable, which loses
	/// every cue rather than one.
	@Test func windowsLineEndingsSurvive() {
		let cues = WebVTT.parse("WEBVTT\r\n\r\n00:00:01.000 --> 00:00:02.000\r\nText\r\n")
		#expect(cues == [Cue(start: 1, end: 2, text: "Text")])
	}

	/// ffmpeg's webvtt muxer carries inline markup through, and nothing here
	/// renders it - so showing it literally would be worse than dropping it.
	@Test func inlineMarkupIsDropped() {
		let cues = WebVTT.parse(
			"""
			WEBVTT

			00:00:01.000 --> 00:00:02.000
			<v Alice><i>Hello</i>
			"""
		)
		#expect(cues.first?.text == "Hello")
	}

	@Test func anEmptyFileHasNoCues() {
		#expect(WebVTT.parse("").isEmpty)
		#expect(WebVTT.parse("WEBVTT\n\n").isEmpty)
	}

	// MARK: - What is on screen

	private let cues = [
		Cue(start: 1, end: 3, text: "One"),
		Cue(start: 3, end: 5, text: "Two"),
		Cue(start: 4, end: 6, text: "Overlapping"),
	]

	@Test func nothingShowsBeforeTheFirstCue() {
		#expect(WebVTT.showing(at: 0.5, in: cues) == nil)
	}

	/// **The end is exclusive**, so two cues that abut do not both show for the
	/// instant they share - which would flicker a doubled line at every
	/// boundary.
	@Test func abuttingCuesDoNotBothShow() {
		#expect(WebVTT.showing(at: 3, in: cues) == "Two")
	}

	/// Genuinely overlapping cues both show, because that is what overlapping
	/// means - dropping one would silently lose a speaker.
	@Test func overlappingCuesShowTogether() {
		#expect(WebVTT.showing(at: 4.5, in: cues) == "Two\nOverlapping")
	}

	@Test func nothingShowsInAGap() {
		#expect(WebVTT.showing(at: 6.5, in: cues) == nil)
	}
}
